### ISSUE TITLE
cpp is not the only extension for C++

### ISSUE THREAD

**Issue by ztdwu** [kbknapp/cargo-count#19]
``` c++
{ ".cc", ".cpp", ".cp", ".cxx", ".c++", ".C" }
```

As far as I know, these are all [valid extensions](http://stackoverflow.com/a/3223792) for C++ source code, with `cc` and `cpp` being the most popular. Currently `cargo-count` only supports `cpp`.

**Comment by Vinatorul** [comment]
Thank you for your contibution!
Yeah, there are more valid extensions for other languages, too, `.htm` for `html`, `.h++, .h` for `c++` headers, etc.
It will be done when @kbknapp or I will have some free time :wink:
I think I can try it tonight or tommorow.

**Comment by kbknapp** [comment]
@Vinatorul should be as easy as adding another line(s) below [this one](https://github.com/kbknapp/cargo-count/blob/ae21af69bd7b667e6adfd3a561d7d1421449a6d0/src/language.rs#L28) with the additional extensions.

**edit**: fixed link

**Comment by ztdwu** [comment]
I don't think the fix quite worked.

```
> touch a.cc
> touch a2.cc
> touch a3.cc
> ls
a.cc a2.cc a3.cc

> ~/workspace/cargo-count/target/release/cargo-count count 
Gathering information...
         Language  Files  Lines  Blanks  Comments  Code
         --------  -----  -----  ------  --------  ----
         C++       1      0      0       0         0
         C++       1      0      0       0         0
         C++       1      0      0       0         0
         --------  -----  -----  ------  --------  ----
Totals:            3      0      0       0         0
```

**Comment by m-n** [comment]
I think the multiple `C++` printed lines is fixed on master, but hasn't been published to crates.io yet.

**Comment by kbknapp** [comment]
@m-n I apologise. I'm pushing some updates now, and I'll upload the new version to crates.io.

**Comment by m-n** [comment]
@kbknapp Thanks. I don't intend to rush you; I wanted to make sure the status of the issue was clear.

**Comment by nabijaczleweli** [comment]
This is fixed when you release current `HEAD`
