### ISSUE TITLE
Ensure "unsafe" counts

### ISSUE THREAD

**Issue by kbknapp** [kbknapp/cargo-count#5]
The unsafe counter probably isn't counting all the unsafe lines due to a crappy regex, and _maybe_ due to bad bracket counting after finding unsafe blocks.

`grep`ing for `unsafe {` (even those lines that don't contain `//` at all, much less to say in correct places that _should_ lead to commented out unsafe) in the Rust repo leads to ~2,000. Now consider some of those are the _start_ of an unsafe block. So there should be around 2,000+ unsafe lines when running `cargo count`, yet currently it reports only ~1,200.

**Comment by azerupi** [comment]
`unsafe` is not always followed by brackets. Example from the nomicon:

``` rust
unsafe impl<T: Send> Send for Unique<T> {}
```

**Comment by kbknapp** [comment]
Yep, the actual regex doesn't assume that it will be. In fact, the goal is mark and count the entire function as unsafe when used to mark a function and not a block. 

I have a stash locally that I'm working on with a far more accurate regex and counting function, but it isn't 100% correct....so if you have a solution I'm all ears ;)

**Comment by azerupi** [comment]
Ah sorry, from the issue I assumed that it only matched blocks. My bad :)

If I had no exams I would have tried to help more but until end august I am
a bit in a rush ;)

**Comment by kbknapp** [comment]
No worries! :)

After going through my [latest Rust checkout](https://github.com/rust-lang/rust/commit/5e5b99f47f4d96d2e3fabd05dc5a128a41245187) (which I'll use as my "official" guide for correctness on this issue) with some crazy `grep`ping I've found 2861 lines that I believe are valid `unsafe` lines. What I _don't_ know is how many of those lines are inside of `/* block comments */` which will get ruled out by the counting function....but let's just say 2861 for the sake of argument. 

Since a large majority of those lines are actually _starting_ unsafe blocks, `cargo-count` should probably have a significant number above that.
